### Service bus ###
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: service-bus
  name: service-bus
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: service-bus
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: service-bus
  name: service-bus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-bus
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: service-bus
    spec:
      containers:
        - env:
            - name: REDIS_HOSTNAME
              value: soa-msg-q
          image: zorfeas/soa-servicebus:latest
          name: service-bus
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
