### Web frontend ###
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 5000
      nodePort: 32080
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: REACT_APP_ACCOUNT_URL
              value: http://saas-15.ddns.net:3003/ama-services/account
            - name: REACT_APP_ANSWER_URL
              value: http://saas-15.ddns.net:3003/ama-services/answer
            - name: REACT_APP_AUTH_URL
              value: http://saas-15.ddns.net:3003/authenticator
            - name: REACT_APP_BROWSE_URL
              value: http://saas-15.ddns.net:3003/ama-services/browse
            - name: REACT_APP_QUESTION_URL
              value: http://saas-15.ddns.net:3003/ama-services/question
          image: zorfeas/soa-web:latest
          name: web
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
