### Authenticator microservice ###
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: authenticator
  name: authenticator
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    io.kompose.service: authenticator
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: authenticator
  name: authenticator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: authenticator
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: authenticator
    spec:
      containers:
        - env:
            - name: JWT_EXPIRES_IN
              value: 1h
            - name: JWT_SECRET
              value: 49ajfdngak43ksmaam3482ui5lmfa
            - name: PGDATABASE
              value: ms-auth
            - name: PGHOST
              value: psql-db
            - name: PGPASSWORD
              value: "12345"
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: data-manager
            - name: REDIS_HOSTNAME
              value: msg-q
            - name: SALT_ROUNDS
              value: "10"
          image: zorfeas/ms-authenticator:latest
          name: authenticator
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
