version: "3.9"
services:
    services:
        image: zorfeas/soa-services:v0.01
        container_name: services
        environment:
            DL_HOSTNAME: saas-15.ddns.net
            DL_PORT: 3000
            AUTH_HOSTNAME: saas-15.ddns.net
            AUTH_PORT: 3001
        ports:
            - 3002:3000