### Database server microservice ###
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: psql-db
  name: psql-db
spec:
  type: NodePort
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
      nodePort: 31000
  selector:
    io.kompose.service: psql-db
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: psql-db
  name: psql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: psql-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: psql-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: dl-persistence
            - name: POSTGRES_PASSWORD
              value: "12345"
            - name: POSTGRES_USER
              value: data-manager
          image: postgres:9.6.21-alpine
          name: psql-db
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: ms-complete
      restartPolicy: Always
      volumes:
        - name: ms-complete
          persistentVolumeClaim:
            claimName: ms-complete
status: {}
