### Question management microservice ###
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: question-manager
  name: question-manager
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    io.kompose.service: question-manager
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: question-manager
  name: question-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: question-manager
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: question-manager
    spec:
      containers:
        - env:
            - name: AUTH_HOSTNAME
              value: ms-authenticator
            - name: AUTH_PORT
              value: "3000"
            - name: PGDATABASE
              value: ms-questions
            - name: PGHOST
              value: psql-db
            - name: PGPASSWORD
              value: "12345"
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: data-manager
            - name: REDIS_HOSTNAME
              value: ms-msg-q
          image: zorfeas/ms-question-manager:latest
          name: question-manager
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
