version: "3.9"
services:
    service-bus:
        image: zorfeas/soa-servicebus:init
        container_name: service-bus
        environment:
            REDIS_HOSTNAME: msg-q
        depends_on:
            - msg-q
        ports:
            - 3000:3000
    msg-q:
        image: redis:6.2.3-alpine3.13
        container_name: msg-q
        expose:
            - 6379
        