name: (Services) Build & Push image

on:
  push:
    branches: [ main ]
    paths:
      - 'SOA/Services/**'
      - '!SOA/Services/.idea/**'
      - '!SOA/Services/README.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'SOA/Services/**'
      - '!SOA/Services/.idea/**'
      - '!SOA/Services/README.md'
  workflow_dispatch:

defaults:
  run:
    working-directory: SOA/Services
  
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch main or PR-merge-branch on runner
        uses: actions/checkout@v2.3.4
      
      - name: Setup node environment
        run: npm install
      
      - name: Login Docker
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: Setup caching for Docker
        if: github.event_name != 'pull_request'
        uses: actions/cache@v2
        with:
          path: /tmp/services/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Setup Docker Buildx
        if: github.event_name != 'pull_request'
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Setup image tags
        if: github.event_name != 'pull_request'
        run: |
          echo "IMAGE_TAG=$(curl -m 20 'http://snf-880282.vm.okeanos.grnet.gr:60080/docker/soa-services-latest-tag.txt')" >> $GITHUB_ENV

      - name: Build and push image
        if: github.event_name != 'pull_request'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}/SOA/Services
          file: ${{ github.workspace }}/SOA/Services/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/soa-services:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/soa-services:latest
          cache-from: type=local,src=/tmp/services/.buildx-cache
          cache-to: type=local,dest=/tmp/services/.buildx-cache-new

      - name: Pull & restart containers
        if: github.event_name != 'pull_request'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: temp
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: cd ~ && ./update-kube.sh services

      - name: Move cache
        if: github.event_name != 'pull_request'
        run: |
          rm -rf /tmp/services/.buildx-cache
          mv /tmp/services/.buildx-cache-new /tmp/services/.buildx-cache
